spring:
  profiles:
    active: git
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config, classpath:/app1, classpath:/app2
        overrides:
          forbidden: '{cipher}AgA8jhh3DRLf/oCO/RxBPXBDwv6ypyE+p1FdjWRLqZGinPwVDGYCJVDrdQd52ZavCM9VND89xMCq7DN+1jNh9T515WTKr27n8enMlnGO6pzZiEHZZA1afBjr2lOIP6sialRQMB+GuDsJ/lK2xVRkxNYTipcjdars3nd/7a5dp/DcVyj/HtoqgGcVMl6jgX9VbM+9y0KL5ROb+5yxxL7Yyhg5je4Tyr+v/XzZcvRsAGPTJpp6tR0HzsamnPL6zV6TfIb1IZXrdKFF0FtFsyTDZAzZaeUNHTi+wY8a/7ZSNL9mGPMAyDYKJCcPadFq9YPskLLvyIgVdGQmaf7qgV7TlxDbMUHJGpJo6edrbFcZLIJXEplo231WXPY946MOVVb8FyjsH+oxiWzYE9Vn/0w8+ogupP2QX0EWjMjZjtqzev6NF7C0bWY7PEOjLBFrFOCYsjSams7Jb9ihqCOJBd4cua/1i2eACb8LZ3zRCoQsXNRmyYdc3NVXp5CeZb1uPjNkHks5P5VSMqZQJgMAA5dW6X9aLdafzOkfsIlIyL50k8Ff7SRzWjFGodb3MMQgebg0HdaEUpPkpfq8lZmHgg2zDQQrBMKiPllDigK+91+sfF+6ueco4LcN967bGYzsUzKitdZ8/UzkJa8UUJHWfKnP/vXODyOeani+mFJBiCjI/jUNlDt5jdtnbp+ddcw+AJPyZFet9pzdhOQvsb4Qa1GN1Sxo3XlUkQy4su5Ta1m1IwJpdQ=='
        vault:
          kv-version: 2
        git:
          uri: https://github.com/neocxf/neocloud
          search-paths:
            - properties/app*
          force-pull: true
  application:
    name: config
server:
  port: 8888
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
  instance:
    prefer-ip-address: true
    hostname: localhost
