version: '2'
services:
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - 15672:15672
      - 5672:5672
    logging:
      options:
        max-size: "10m"
        max-file: "10"
  config:
    build: config
    container_name: config
    mem_limit: 370
    ports:
      - 8888:8888
    environment:
      - EUREKA_INSTANCE_HOSTNAME=${NEOCLOUD_HOST}
  eureka:
    build: eureka-registry
    container_name: eureka
    mem_limit: 320
    ports:
      - 8761:8761
    environment:
      - EUREKA_INSTANCE_HOSTNAME=${NEOCLOUD_HOST}
    depends_on:
      - config
  util:
    build: util-service
    container_name: util
    mem_limit: 370
    ports:
      - 9003:9003
    environment:
      - EUREKA_INSTANCE_HOSTNAME=${NEOCLOUD_HOST}
      - SPRING_RABBITMQ_HOST=${NEOCLOUD_HOST}
  inventory:
    build: inventory-service
    container_name: inventory
    mem_limit: 320
    ports:
      - 9001:9001
    environment:
      - EUREKA_INSTANCE_HOSTNAME=${NEOCLOUD_HOST}
  gateway:
    build: gateway
    container_name: gateway
    mem_limit: 320
    ports:
      - 8080:8080
    environment:
      - EUREKA_INSTANCE_HOSTNAME=${NEOCLOUD_HOST}
  cart:
    build: cart-service
    container_name: cart
    mem_limit: 370
    ports:
      - 9002:9002
    environment:
      - EUREKA_INSTANCE_HOSTNAME=${NEOCLOUD_HOST}
      - SPRING_RABBITMQ_HOST=${NEOCLOUD_HOST}
    depends_on:
      rabbitmq:
        condition: service_healthy
      inventory:
        condition: service_healthy
      util:
        condition: service_healthy
  catalog:
    build: catalog-service
    container_name: catalog
    mem_limit: 370
    ports:
      - 9005:9005
    environment:
      - EUREKA_INSTANCE_HOSTNAME=${NEOCLOUD_HOST}
  customer:
    build: customer-service
    container_name: customer
    mem_limit: 370
    ports:
      - 9004:9004
    environment:
      - EUREKA_INSTANCE_HOSTNAME=${NEOCLOUD_HOST}
  order:
    build: order-service
    container_name: order
    mem_limit: 370
    ports:
    - 9006:9006
    environment:
    - EUREKA_INSTANCE_HOSTNAME=${NEOCLOUD_HOST}
  mongo:
    build: mongodb
    ports:
      - 27017:27017
    environment:
    - MONGODB_PASSWORD=${MONGODB_PASSWORD}
  auth:
    build: auth-service
    container_name: auth
    mem_limit: 370
    ports:
    - 9007:9007
    environment:
    - EUREKA_INSTANCE_HOSTNAME=${NEOCLOUD_HOST}
    - MONGODB_HOST=${NEOCLOUD_HOST}
    - MONGODB_PASSWORD=${MONGODB_PASSWORD}
    depends_on:
      - mongo