#eureka:
#  client:
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
#  instance:
#    prefer-ip-address: false
#    hostname: localhost
zuul:
  prefix: /api
  routes:
    inventory:
      path: /neo-inventory/**
      serviceId: inventory-service
    cart:
      path: /neo-cart/**
      serviceId: cart-service
    auth:
      path: /neo-auth/**
      serviceId: auth-service
    order:
      path: /neo-order/**
      serviceId: order-service
    catalog:
      path: /neo-catalog/**
      serviceId: catalog-service
    reward:
      path: /neo-reward/**
      serviceId: reward-service
server:
  port: 8081
spring:
  application:
    name: gateway
ribbon:
  eager-load:
    enabled: true