grpc:
  port: 6565
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
  instance:
    prefer-ip-address: true
    hostname: localhost
    non-secure-port: ${grpc.port}
spring:
  application:
    name: neo-util
  rabbitmq:
    host: ${MQ_ADDR:localhost}
    port: 5672
    username: guest
    password: guest
server:
  port: 9003